export const FETCH_ALL_POSTS = 'FETCH_ALL_POSTS';
export const FETCH_POST = 'FETCH_POST';
export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';
export const SET_CATEGORY = 'SET_CATEGORY';
export const CREATE_POST = 'CREATE_POST';
export const FINISH_CREATE_POST = 'FINISH_CREATE_POST';
export const EDIT_POST = 'EDIT_POST';
export const UPDATE_POST = 'UPDATE_POST';
export const CLEAR_POST = 'CLEAR_POST';
export const DELETE_POST = 'DELETE_POST';
export const UPVOTE_POST = 'UPVOTE_POST';
export const DOWNVOTE_POST = 'DOWNVOTE_POST';
export const CANCEL_EDIT = 'CANCEL_EDIT';
export const FINISH_EDIT_POST = 'FINISH_EDIT_POST';
export const SORT = 'SORT';

//Comments
export const FETCH_COMMENTS = 'FETCH_COMMENTS';
export const UPVOTE_COMMENT = 'UPVOTE_COMMENT';
export const DOWNVOTE_COMMENT = 'DOWNVOTE_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const CLEAR_COMMENTS = 'CLEAR_COMMENTS';
export const ADD_COMMENT = 'ADD_COMMENT';
export const EDIT_COMMENT = 'EDIT_COMMENT';
export const FINISH_EDIT = 'FINISH_EDIT';
export const UPDATE_COMMENT = 'UPDATE_COMMENT';

